package com.sede.entities;
// Generated 26 ene 2026, 12:50:10 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable {

	private Integer idEntidad;
	private String nombreEntidad;
	private Set registroses = new HashSet(0);

	public Entidad() {
	}

	public Entidad(String nombreEntidad) {
		this.nombreEntidad = nombreEntidad;
	}

	public Entidad(String nombreEntidad, Set registroses) {
		this.nombreEntidad = nombreEntidad;
		this.registroses = registroses;
	}

	public Integer getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Integer idEntidad) {
		this.idEntidad = idEntidad;
	}

	public String getNombreEntidad() {
		return this.nombreEntidad;
	}

	public void setNombreEntidad(String nombreEntidad) {
		this.nombreEntidad = nombreEntidad;
	}

	public Set getRegistroses() {
		return this.registroses;
	}

	public void setRegistroses(Set registroses) {
		this.registroses = registroses;
	}

}
