package com.sede.entities;
// Generated 26 ene 2026, 12:50:10 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Registros generated by hbm2java
 */
public class Registros implements java.io.Serializable {

	private String numRegistro;
	private Entidad entidad;
	private String dniSolicitante;
	private String nombreSolicitante;
	private String apellidosSolicitante;
	private String tramite;
	private Timestamp fechaRegistro;

	public Registros() {
	}

	public Registros(String numRegistro, Entidad entidad, String dniSolicitante, String nombreSolicitante,
			String apellidosSolicitante, String tramite, Timestamp fechaRegistro) {
		this.numRegistro = numRegistro;
		this.entidad = entidad;
		this.dniSolicitante = dniSolicitante;
		this.nombreSolicitante = nombreSolicitante;
		this.apellidosSolicitante = apellidosSolicitante;
		this.tramite = tramite;
		this.fechaRegistro = fechaRegistro;
	}

	public String getNumRegistro() {
		return this.numRegistro;
	}

	public void setNumRegistro(String numRegistro) {
		this.numRegistro = numRegistro;
	}

	public Entidad getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	public String getDniSolicitante() {
		return this.dniSolicitante;
	}

	public void setDniSolicitante(String dniSolicitante) {
		this.dniSolicitante = dniSolicitante;
	}

	public String getNombreSolicitante() {
		return this.nombreSolicitante;
	}

	public void setNombreSolicitante(String nombreSolicitante) {
		this.nombreSolicitante = nombreSolicitante;
	}

	public String getApellidosSolicitante() {
		return this.apellidosSolicitante;
	}

	public void setApellidosSolicitante(String apellidosSolicitante) {
		this.apellidosSolicitante = apellidosSolicitante;
	}

	public String getTramite() {
		return this.tramite;
	}

	public void setTramite(String tramite) {
		this.tramite = tramite;
	}

	public Timestamp getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Timestamp fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
